import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/AppIcons";
import TransitionEffect from "@/components/TransitionEffect";
import ContactForm from "@/components/ContactForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - IBassemTarek</title>
        <meta name="description" content="Generated by IBassemTarek" />
        <meta name="google-site-verification" content="ypEHRoJMh52hPC3nL6q6Xaa5ZMHj2Fl0mm5lvYja_Ss" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className={"pt-0 md:p-16 sm:pt-8"}>
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 aspect-[16/9] md:block md:w-full lg:hidden">
              <Image
                src={profilePic}
                alt="Bassem Tarek Mahrous, full-stack developer"
                className="h-auto w-full"
                priority
                sizes="(max-width: 639px) 100vw, 
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
                text={"Dreams Coded, Visions Designed."}
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative software applications. Explore my latest
                projects, showcasing my expertise in software development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark 
                  hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light
                  md:p-2 md:px-4 md:text-base
                  "
                  href={"/BassemTarekMahrousResume.pdf"}
                  target={"_blank"}
                  rel="noreferrer"
                  aria-label="Open Bassem Tarek Mahrous resume PDF"
                >
                  Resume <LinkArrow className={"w-6 ml-2"} />
                </Link>
                <Link
                  href={"#contact"}
                  aria-label="Jump to contact form"
                  className="ml-4 text-lg font-medium capitalize text-dark group relative dark:text-light md:text-base"
                >
                  Contact
                  <span
                    className={`w-0 h-[2px] inline-block bg-black absolute left-0 -bottom-0.5 group-hover:w-full transition-[width] ease duration-300 dark:bg-light`}
                  >
                    &nbsp;
                  </span>
                </Link>
              </div>
            </div>
          </div>
          <ContactForm />
        </Layout>
      </main>
    </>
  );
}
